### ISSUE TITLE
Amazing and some question

### ISSUE THREAD

**Issue by greatbody** [Salvoxia/docker-openvpn-tap#10]
Can you explain the attributes from the command?

```
docker run -v $OVPN_DATA:/etc/openvpn --rm salvoxia/openvpn-tap \
  ovpn_genconfig \
      -u udp://VPN.SERVERNAME.COM:PORT \
      -t \
      -B \
      --bridge-name 'br0' \
      --bridge-eth-if 'eth0' \
      --bridge-eth-ip '192.168.0.199' \
      --bridge-eth-subnet '255.255.255.0' \
      --bridge-eth-broadcast '192.168.0.255' \
      --bridge-eth-gateway '192.168.0.1' \
      --bridge-eth-mac 'b8:32:ac:8b:17:2e' \
      --bridge-dhcp-start '192.168.0.200' \
      --bridge-dhcp-end '192.168.0.220'
```

This is what I get from LLM

```md
I'll break down this Docker command and explain each part in detail:

1. Base Docker command:
```bash
docker run -v $OVPN_DATA:/etc/openvpn --rm salvoxia/openvpn-tap
```
- `docker run`: Starts a new container
- `-v $OVPN_DATA:/etc/openvpn`: Mounts a volume, where `$OVPN_DATA` (local directory) is mapped to `/etc/openvpn` inside the container
- `--rm`: Automatically removes the container when it exits
- `salvoxia/openvpn-tap`: The Docker image name, a modified version of OpenVPN that supports TAP mode

2. The `ovpn_genconfig` command with options:
- `-u udp://VPN.SERVERNAME.COM:PORT`: Specifies the UDP protocol, server hostname, and port for the VPN
- `-t`: Enables TAP mode (Layer 2) instead of the default TUN mode (Layer 3)
- `-B`: Enables bridging mode

3. Bridge configuration parameters:
- `--bridge-name 'br0'`: Sets the bridge interface name to 'br0'
- `--bridge-eth-if 'eth0'`: Specifies the physical network interface to bridge (eth0)
- `--bridge-eth-ip '192.168.0.199'`: Sets the IP address for the bridge
- `--bridge-eth-subnet '255.255.255.0'`: Sets the subnet mask (255.255.255.0 = /24)
- `--bridge-eth-broadcast '192.168.0.255'`: Defines the broadcast address
- `--bridge-eth-gateway '192.168.0.1'`: Specifies the default gateway
- `--bridge-eth-mac 'b8:32:ac:8b:17:2e'`: Sets the MAC address for the bridge interface
- `--bridge-dhcp-start '192.168.0.200'`: Starting IP for DHCP range
- `--bridge-dhcp-end '192.168.0.220'`: Ending IP for DHCP range

Key aspects of this configuration:
1. This setup creates a TAP-mode VPN, which operates at Layer 2 (ethernet level) instead of Layer 3 (IP level)
2. It sets up a bridge interface that connects the VPN network with the physical network
3. The DHCP server will assign IPs from .200 to .220 in the 192.168.0.0/24 network
4. VPN clients will appear as if they're directly connected to the local network (192.168.0.0/24)
5. This configuration allows for ethernet-level protocols to work across the VPN, which is useful for scenarios requiring broadcast/multicast support or direct Layer 2 access

This setup would be particularly useful for:
- Gaming networks requiring LAN-like connectivity
- Networks requiring broadcast/multicast support
- Environments where VPN clients need to appear as if they're physically connected to the local network
- Scenarios requiring direct Layer 2 network access
```

**Comment by Salvoxia** [comment]
The LLM's explanation is pretty much spot on.
When setting up the container you work in two phases:
1. You create the OpenVPN Server's configuration by running the command you posted without actually starting the container. This will create a configuration for the server along with the server's certificate it uses to sign client certificates with. Everything is stored in the mounted volume.
2. You start up the container, which in turn starts the OpenVPN Server using the configuration you created in step 1.

When creating the configuration you need to adjust the command to suit your environment:
  - `-u` is your public IP address/domain and port that is forwarded to the Docker container so you can actually connect from outside your network
  - `--bridge-name` only needs to be changed if you already have a `br0` interface and need to change the name
  - `--bridge-eth-if` needs to be the name of your Docker host's network interface that is connected to the network you want your VPN clients join to
  - `--bridge-eth-ip` is the IP address your Docker host is configured to (should be static), since the bridge will "replace" the host's network interface when facing the network
  - `--bridge-eth-subnet` for most home networks no changes are needed here
  - `--bridge-eth-broadcast` depends on your network's subnet, usually it's your host's IP address, but ending with `255`,
  - `--bridge-eth-gateway` usually our (ISP's) router address in your network
  - `--bridge-eth-mac` the MAC address the bridge will show up on your network with, you could set it to the same address as your physical network interface
  - `--bridge-dhcp-start` and `--bridge-dhcp-end` define the range of IP addresses the VPN clients can be assigned. Must not overlap with your internal DHCP server's address range to prevent duplicate IP address assignment.


If you could be more specific about which parts you don't understand or would like to know more about I can give a more precise answer.

**Comment by greatbody** [comment]
Thanks a lot for the explanation.

```
docker run -v $OVPN_DATA:/etc/openvpn --rm salvoxia/openvpn-tap \
  ovpn_genconfig \
      -u udp://vpn.example.ink:1190 \
      -t \
      -B \
      --bridge-eth-if 'ens160' \     # the interface my host using to access internet, this host does not have public ip, but my router does and will forward port 1190 to this host
      --bridge-eth-ip '10.10.11.11' \
      --bridge-eth-subnet '255.255.255.0' \
      --bridge-eth-broadcast '10.10.11.255' \
      --bridge-eth-gateway '10.10.11.1' \
      --bridge-eth-mac '00:0c:29:6d:06:ac' \
      --bridge-dhcp-start '10.10.11.131' \
      --bridge-dhcp-end '10.10.11.200'
```
After this configuration I connected my laptop to a wifi shared by my phone which connected to Cell phone network instead of my home network, to simulate I am outside of my home. I was able to connect to my OpenVPN server and get an internet IP address, which is cool, I can ssh to the host where I run this openvpn-tap docker, however, I cannot connect to other devices in my home network.

Do you now which could be the cause.

Thanks a lot!

----

More context:

My router, which is connected to the public network with a public IP address, has the IP address 10.10.11.1. The device with the IP address 10.10.11.3 is my secondary router.

I run my openvpn-tap on 10.10.11.11 which sets 10.10.11.3 as its gateway, and 10.10.11.3 use 10.10.11.1 as its gateway.
10.10.11.3 runs OpenWrt Kwrt 09.26.2024 by Kiddin

**Comment by greatbody** [comment]
@Salvoxia Your container is excellent. I identified the root cause: I am using ESXi in my home-lab and needed to enable Promiscuous mode on the virtual switch (VSwitch) connected to the VM. After making this configuration change and rebooting, the Docker started working perfectly. I can detect home-lab SMB shares from office using this VPN.

**Comment by Salvoxia** [comment]
Great to hear you figured it out!
Do you have any other questions or problems? Otherwise, please close the issue.
